version: '3.7'

services:
  devicedb:
    image: mongo

  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - acmeapi
      - frontend
    ports:
      - '8080:80'

  acmeapi:
    build:
      context: .
      dockerfile: Acme.API/Dockerfile

  frontend:
    build:
      context: ./frontend
    command: yarn start
    ports:
      - '3000:3000'
    depends_on:
      - devicedb
      - acmeapi
    tty: true
    stdin_open: true
    environment:
      - REACT_APP_API_PORT=8080
      - REACT_APP_API_URL=acmeapi
