version: '3.7'

services:
      
  devicedb:
    image: mongo


  nginx:
    image: nginx:stable-alpine
    ports:
     - '8080:80'
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  acmeapi:
    image: acmeapi    
    build:
      context: .
      dockerfile: Acme.API/Dockerfile



  frontend:
    build:
      context: ./frontend
    command: yarn start
    ports:
      - '3000:3000'
    depends_on:
      - devicedb
      - acmeapi
    tty: true
    stdin_open: true
    environment:
      - REACT_APP_API_PORT=8090
      - REACT_APP_API_URL=acmeapi

