version: '3.7'

services:
  devicedb:
    container_name: devicedb
    restart: always
    ports:
      - '27017:27017'

  acmeapi:
    container_name: acmeapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'DeviceDatabaseSettings:ConnectionString=mongodb://devicedb:27017'
    depends_on:
      - devicedb
    ports:
      - '8000:8090'
